In [1]:

import sys
import types

# --- STEP 1: Fool Pickle by creating a fake 'features' module in memory ---
fake_module = types.ModuleType("features")
sys.modules["features"] = fake_module


# Tell Python how to unpack the custom object into a dummy class
class DummyQueryFeatures:

    def __setstate__(self, state):
        self.__dict__.update(state)


fake_module.QueryFeatures = DummyQueryFeatures

# --- STEP 2: Now, load your pickle file ---
import pandas as pd

saved_data = pd.read_pickle("F:/code_experiment/models/pa_query_data.pkl")

# Extract your variables from the saved dict
feature_rows = saved_data["feature_rows"]
labels = saved_data["labels"]
meta = saved_data["meta"]

# --- STEP 3: Flatten the objects into standard rows/columns ---
flat_rows = []
for feat, label, m in zip(feature_rows, labels, meta):
    # Get the attributes out of our dummy Python object
    row_data = feat.__dict__.copy()

    # Add the target label and metadata keys
    row_data["target_label"] = label
    row_data.update(m)

    flat_rows.append(row_data)

# Create a clean DataFrame (only strings, numbers, booleans)
df_clean = pd.DataFrame(flat_rows)

In [12]:
%pip install jupysql duckdb-engine --quiet

Note: you may need to restart the kernel to use updated packages.

WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
%load_ext sql

In [3]:
%sql duckdb:///:memory:

Connecting to 'duckdb:///:memory:'

In [5]:
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False
%config SqlMagic.displaycon = False

In [6]:
import duckdb

# 1. Create a native DuckDB connection
conn = duckdb.connect()

# 2. Pass this active connection to JupySQL
%sql conn --alias duckdb

In [8]:
%%sql
SELECT has_relevant_index, count(*) as count 
FROM df_clean
group by has_relevant_index
;

   has_relevant_index  count
0               False     25
1                True      6

In [9]:
%%sql
SELECT *
FROM df_clean
;

,node_type,estimated_cost,estimated_rows,plan_width,tables,table_count,filtered_seq_scan_count,index_scan_count,has_relevant_index,seconds_since_last_analyze,n_mod_since_analyze,n_live_tup,is_cross_join,join_count,target_label,label,actual_rows,misestimated
0,Aggregate,4.224162e+05,6.000000e+00,236.0,[lineitem],1,1,0,False,59.240911,0,10987239,False,0,0,Q01,4.000000e+00,False
1,Limit,2.417405e+06,1.000000e+00,192.0,"[part, region, supplier, nation, partsupp]",5,2,5,False,302.657545,0,10065650,True,7,1,Q02,1.000000e+02,True
2,Limit,7.061181e+05,1.000000e+01,44.0,"[lineitem, orders, customer]",3,3,0,False,353.957377,0,22485719,False,2,0,Q03,1.000000e+01,False
3,Aggregate,3.580059e+05,5.000000e+00,24.0,"[orders, lineitem]",2,0,3,False,376.419898,0,20985954,True,1,0,Q04,5.000000e+00,False
4,Sort,4.194206e+05,2.500000e+01,58.0,"[customer, nation, region, orders, lineitem, s...",6,1,2,False,723.953922,0,22585749,True,5,1,Q05,5.000000e+00,True
5,Aggregate,3.105419e+05,1.000000e+00,32.0,[lineitem],1,1,0,False,728.616644,0,10987239,False,0,0,Q06,1.000000e+00,False
6,Aggregate,4.028719e+05,1.002800e+04,116.0,"[customer, nation, orders, lineitem, supplier]",5,3,1,False,880.844542,0,22585744,True,5,1,Q07,4.000000e+00,True
7,Aggregate,2.214583e+05,2.406000e+03,64.0,"[part, lineitem, orders, customer, nation, reg...",7,2,4,False,923.678334,0,24585764,True,7,1,Q08,2.000000e+00,True
8,Aggregate,5.110945e+05,2.300000e+01,90.0,"[partsupp, part, lineitem, supplier, orders, n...",6,1,4,False,1192.571327,0,31051599,True,5,1,Q09,1.750000e+02,True
9,Limit,5.609227e+05,2.000000e+01,201.0,"[lineitem, orders, customer, nation]",4,1,3,False,1250.381650,0,22485744,True,3,0,Q10,2.000000e+01,False
10,Sort,1.122105e+05,1.056910e+05,36.0,"[supplier, nation, partsupp]",3,2,4,False,1357.421933,0,8065630,True,4,1,Q11,0.000000e+00,True
11,Aggregate,4.458963e+05,7.000000e+00,27.0,"[lineitem, orders]",2,1,1,False,1376.625763,0,20985954,True,1,1,Q12,2.000000e+00,True
12,Sort,1.151129e+06,2.000000e+02,16.0,"[orders, customer]",2,1,1,False,1501.690101,0,11498480,False,1,1,Q13,3.400000e+01,True
13,Aggregate,3.035688e+05,1.000000e+00,32.0,"[part, lineitem]",2,0,2,True,1508.520389,0,12987254,False,1,0,Q14,1.000000e+00,False
14,Nested Loop,3.298611e+05,4.860000e+02,103.0,"[lineitem, supplier]",2,0,3,True,1525.709694,0,11087239,True,1,1,Q15,1.000000e+00,True
15,Sort,3.799815e+05,1.540780e+05,44.0,"[partsupp, supplier, part]",3,2,1,False,1556.913265,0,10065620,False,1,1,Q16,2.784000e+04,True
16,Aggregate,3.995975e+05,1.000000e+00,32.0,"[lineitem, part]",2,1,1,False,1582.637928,0,12987254,False,1,0,Q17,1.000000e+00,False
17,Limit,1.339999e+06,1.000000e+02,71.0,"[orders, lineitem, customer]",3,0,2,False,1719.459522,0,22485719,True,3,0,Q18,1.000000e+02,False
18,Aggregate,1.370305e+05,1.000000e+00,32.0,"[part, lineitem]",2,1,1,False,1719.471883,0,12987254,True,1,0,Q19,1.000000e+00,False
19,Nested Loop,2.775201e+06,1.068000e+03,51.0,"[supplier, nation, partsupp, lineitem, part]",5,1,3,False,1943.114956,0,21052884,True,3,0,Q20,6.310000e+02,False
20,Limit,5.457637e+05,1.000000e+00,34.0,"[lineitem, nation, supplier, orders]",4,3,4,False,1987.325726,0,21085979,True,5,1,Q21,1.000000e+02,True
21,Aggregate,1.135719e+05,8.000000e+03,72.0,"[customer, orders]",2,2,1,False,2002.650704,0,11498480,True,1,1,Q22,7.000000e+00,True
22,Gather,2.427154e+05,4.999400e+04,8.0,[orders],1,1,0,True,2000.394868,0,9998715,False,0,1,stmt_1,1.521599e+06,True
23,Aggregate,2.518249e+05,1.000000e+00,8.0,[lineitem],1,0,2,False,2019.394129,0,10987239,False,0,0,stmt_2,1.000000e+00,False
24,Nested Loop,3.880000e+00,1.250000e+02,52.0,"[nation, region]",2,0,0,True,2019.376713,0,30,True,1,0,stmt_3,1.250000e+02,False
25,Aggregate,3.365858e+05,1.000000e+00,8.0,"[orders, customer]",2,0,0,False,2090.737780,0,11498480,False,1,0,stmt_4,1.000000e+00,False
26,Aggregate,3.520997e+05,1.000000e+00,8.0,"[customer, orders, nation, lineitem]",4,0,3,True,2116.316998,0,22485744,True,3,0,stmt_5,1.000000e+00,False
27,Aggregate,2.643226e+05,1.000000e+00,8.0,[lineitem],1,1,0,False,2132.525759,0,10987239,False,0,0,stmt_6,1.000000e+00,False
28,Aggregate,5.657604e+04,1.000000e+00,8.0,[part],1,1,0,False,2128.906592,0,2000015,False,0,0,stmt_7,1.000000e+00,False
29,Nested Loop,7.172998e+06,5.493600e+08,275.0,"[lineitem, customer]",2,2,0,False,13404.609166,0,12487004,True,1,1,QX_EXPENSIVE_01,3.337709e+10,True
30,Nested Loop,4.173204e+08,3.337709e+10,250.0,"[partsupp, orders]",2,0,0,True,24963.972788,0,17964320,True,1,0,QX_EXPENSIVE_02,3.337709e+10,False

In [48]:
df_clean.dtypes

node_type                         str
estimated_cost                float64
estimated_rows                float64
plan_width                    float64
tables                         object
table_count                     int64
filtered_seq_scan_count         int64
index_scan_count                int64
has_relevant_index             object
seconds_since_last_analyze    float64
n_mod_since_analyze             int64
n_live_tup                      int64
is_cross_join                    bool
join_count                      int64
target_label                    int64
label                             str
actual_rows                   float64
misestimated                     bool
dtype: object

In [50]:

import sys
import types

# --- STEP 1: Fool Pickle by creating a fake 'features' module in memory ---
fake_module = types.ModuleType("features")
sys.modules["features"] = fake_module


# Tell Python how to unpack the custom object into a dummy class
class DummyQueryFeatures:

    def __setstate__(self, state):
        self.__dict__.update(state)


fake_module.QueryFeatures = DummyQueryFeatures

# --- STEP 2: Now, load your pickle file ---

import pandas as pd

saved_data = pd.read_pickle("F:/code_experiment/models/query_data.pkl")
pa_saved_data = pd.read_pickle("F:/code_experiment/models/pa_query_data.pkl")



# Convert saved_data to DataFrame if it is a dictionary
if isinstance(saved_data, dict):
    saved_data = pd.DataFrame([saved_data])  # Use [saved_data] if it's a single row, or pd.DataFrame(saved_data) if it's a dict of lists

# Convert pa_saved_data to DataFrame if it is a dictionary
if isinstance(pa_saved_data, dict):
    pa_saved_data = pd.DataFrame([pa_saved_data])
    

# union_df = pd.concat([saved_data, pa_saved_data], ignore_index=True)

In [ ]:
# Extract your variables from the saved dict
feature_rows = saved_data["feature_rows"] 
labels = saved_data["labels"] 
meta = saved_data["meta"] 

# --- STEP 3: Flatten the objects into standard rows/columns ---
flat_rows = []
for feat, label, m in zip(feature_rows, labels, meta):
    print(feat, label, m)
    # Get the attributes out of our dummy Python object
    row_data = feat.__dict__.copy()

    # Add the target label and metadata keys
    row_data["target_label"] = label
    row_data.update(m)

    flat_rows.append(row_data)

# Create a clean DataFrame (only strings, numbers, booleans)
df_clean = pd.DataFrame(flat_rows)

<class '__main__.DummyQueryFeatures'> 0 {'label': 'Q01', 'tables': ('lineitem',), 'estimated_rows': 6.0, 'actual_rows': 4.0, 'misestimated': False}
<class '__main__.DummyQueryFeatures'> 1 {'label': 'Q02', 'tables': ('part', 'region', 'nation', 'supplier', 'partsupp'), 'estimated_rows': 1.0, 'actual_rows': 100.0, 'misestimated': True}
<class '__main__.DummyQueryFeatures'> 0 {'label': 'Q03', 'tables': ('lineitem', 'orders', 'customer'), 'estimated_rows': 10.0, 'actual_rows': 10.0, 'misestimated': False}
<class '__main__.DummyQueryFeatures'> 0 {'label': 'Q04', 'tables': ('orders', 'lineitem'), 'estimated_rows': 5.0, 'actual_rows': 5.0, 'misestimated': False}
<class '__main__.DummyQueryFeatures'> 1 {'label': 'Q05', 'tables': ('supplier', 'customer', 'nation', 'region', 'orders', 'lineitem'), 'estimated_rows': 25.0, 'actual_rows': 5.0, 'misestimated': True}
<class '__main__.DummyQueryFeatures'> 0 {'label': 'Q06', 'tables': ('lineitem',), 'estimated_rows': 1.0, 'actual_rows': 1.0, 'misestimated': False}
<class '__main__.DummyQueryFeatures'> 1 {'label': 'Q07', 'tables': ('lineitem', 'supplier', 'nation', 'orders', 'customer'), 'estimated_rows': 10020.0, 'actual_rows': 4.0, 'misestimated': True}
<class '__main__.DummyQueryFeatures'> 1 {'label': 'Q08', 'tables': ('customer', 'nation', 'region', 'orders', 'lineitem', 'part', 'supplier'), 'estimated_rows': 888.0, 'actual_rows': 2.0, 'misestimated': True}
<class '__main__.DummyQueryFeatures'> 1 {'label': 'Q09', 'tables': ('partsupp', 'part', 'lineitem', 'supplier', 'orders', 'nation'), 'estimated_rows': 16.0, 'actual_rows': 175.0, 'misestimated': True}
<class '__main__.DummyQueryFeatures'> 0 {'label': 'Q10', 'tables': ('lineitem', 'orders', 'customer', 'nation'), 'estimated_rows': 20.0, 'actual_rows': 20.0, 'misestimated': False}
<class '__main__.DummyQueryFeatures'> 1 {'label': 'Q11', 'tables': ('supplier', 'nation', 'partsupp'), 'estimated_rows': 106206.0, 'actual_rows': 0.0, 'misestimated': True}
<class '__main__.DummyQueryFeatures'> 1 {'label': 'Q12', 'tables': ('lineitem', 'orders'), 'estimated_rows': 7.0, 'actual_rows': 2.0, 'misestimated': True}
<class '__main__.DummyQueryFeatures'> 1 {'label': 'Q13', 'tables': ('orders', 'customer'), 'estimated_rows': 200.0, 'actual_rows': 34.0, 'misestimated': True}
<class '__main__.DummyQueryFeatures'> 0 {'label': 'Q14', 'tables': ('part', 'lineitem'), 'estimated_rows': 1.0, 'actual_rows': 1.0, 'misestimated': False}
<class '__main__.DummyQueryFeatures'> 1 {'label': 'Q15', 'tables': ('lineitem', 'supplier'), 'estimated_rows': 485.0, 'actual_rows': 1.0, 'misestimated': True}
<class '__main__.DummyQueryFeatures'> 1 {'label': 'Q16', 'tables': ('partsupp', 'supplier', 'part'), 'estimated_rows': 154763.0, 'actual_rows': 27840.0, 'misestimated': True}
<class '__main__.DummyQueryFeatures'> 0 {'label': 'Q17', 'tables': ('lineitem', 'part'), 'estimated_rows': 1.0, 'actual_rows': 1.0, 'misestimated': False}
<class '__main__.DummyQueryFeatures'> 0 {'label': 'Q18', 'tables': ('orders', 'lineitem', 'customer'), 'estimated_rows': 100.0, 'actual_rows': 100.0, 'misestimated': False}
<class '__main__.DummyQueryFeatures'> 0 {'label': 'Q19', 'tables': ('part', 'lineitem'), 'estimated_rows': 1.0, 'actual_rows': 1.0, 'misestimated': False}
<class '__main__.DummyQueryFeatures'> 0 {'label': 'Q20', 'tables': ('supplier', 'nation', 'partsupp', 'lineitem', 'part'), 'estimated_rows': 1073.0, 'actual_rows': 631.0, 'misestimated': False}
<class '__main__.DummyQueryFeatures'> 1 {'label': 'Q21', 'tables': ('lineitem', 'nation', 'supplier', 'orders'), 'estimated_rows': 1.0, 'actual_rows': 100.0, 'misestimated': True}
<class '__main__.DummyQueryFeatures'> 1 {'label': 'Q22', 'tables': ('customer', 'orders'), 'estimated_rows': 8475.0, 'actual_rows': 7.0, 'misestimated': True}
<class '__main__.DummyQueryFeatures'> 1 {'label': 'stmt_1', 'tables': ('orders',), 'estimated_rows': 50004.0, 'actual_rows': 1521599.0, 'misestimated': True}
<class '__main__.DummyQueryFeatures'> 0 {'label': 'stmt_2', 'tables': ('lineitem',), 'estimated_rows': 1.0, 'actual_rows': 1.0, 'misestimated': False}
<class '__main__.DummyQueryFeatures'> 0 {'label': 'stmt_3', 'tables': ('nation', 'region'), 'estimated_rows': 125.0, 'actual_rows': 125.0, 'misestimated': False}
<class '__main__.DummyQueryFeatures'> 0 {'label': 'stmt_4', 'tables': ('orders', 'customer'), 'estimated_rows': 1.0, 'actual_rows': 1.0, 'misestimated': False}
<class '__main__.DummyQueryFeatures'> 0 {'label': 'stmt_5', 'tables': ('customer', 'orders', 'nation', 'lineitem'), 'estimated_rows': 1.0, 'actual_rows': 1.0, 'misestimated': False}
<class '__main__.DummyQueryFeatures'> 0 {'label': 'stmt_6', 'tables': ('lineitem',), 'estimated_rows': 1.0, 'actual_rows': 1.0, 'misestimated': False}
<class '__main__.DummyQueryFeatures'> 0 {'label': 'stmt_7', 'tables': ('part',), 'estimated_rows': 1.0, 'actual_rows': 1.0, 'misestimated': False}
<class '__main__.DummyQueryFeatures'> 1 {'label': 'QX_EXPENSIVE_01', 'tables': ('lineitem', 'customer'), 'estimated_rows': 549280000.0, 'actual_rows': 33377090000.0, 'misestimated': True}
<class '__main__.DummyQueryFeatures'> 0 {'label': 'QX_EXPENSIVE_02', 'tables': ('partsupp', 'orders'), 'estimated_rows': 33377090000.0, 'actual_rows': 33377090000.0, 'misestimated': False}

<class 'list'>

In [ ]:
# Extract your variables from the saved dict
feature_rows =  [value for values in saved_data["feature_rows"] + pa_saved_data["feature_rows"] for value in values]
labels = [value for values in saved_data["labels"] + pa_saved_data["labels"] for value in values]
meta =  [value for values in saved_data["meta"] + pa_saved_data["meta"] for value in values]

# --- STEP 3: Flatten the objects into standard rows/columns ---
flat_rows = []
for feat, label, m in zip(feature_rows, labels, meta):
    print(feat, label, m)
    # Get the attributes out of our dummy Python object
    row_data = feat.__dict__.copy()

    # Add the target label and metadata keys
    row_data["target_label"] = label
    row_data.update(m)

    flat_rows.append(row_data)

# Create a clean DataFrame (only strings, numbers, booleans)
df_clean = pd.DataFrame(flat_rows)

<__main__.DummyQueryFeatures object at 0x000001F96CA6FCB0> 0 {'label': 'Q01', 'tables': ('lineitem',), 'estimated_rows': 6.0, 'actual_rows': 4.0, 'misestimated': False}
<__main__.DummyQueryFeatures object at 0x000001F96467A490> 1 {'label': 'Q02', 'tables': ('part', 'region', 'nation', 'supplier', 'partsupp'), 'estimated_rows': 1.0, 'actual_rows': 100.0, 'misestimated': True}
<__main__.DummyQueryFeatures object at 0x000001F96467A850> 0 {'label': 'Q03', 'tables': ('lineitem', 'orders', 'customer'), 'estimated_rows': 10.0, 'actual_rows': 10.0, 'misestimated': False}
<__main__.DummyQueryFeatures object at 0x000001F96CB26D70> 0 {'label': 'Q04', 'tables': ('orders', 'lineitem'), 'estimated_rows': 5.0, 'actual_rows': 5.0, 'misestimated': False}
<__main__.DummyQueryFeatures object at 0x000001F96CB268B0> 1 {'label': 'Q05', 'tables': ('supplier', 'customer', 'nation', 'region', 'orders', 'lineitem'), 'estimated_rows': 25.0, 'actual_rows': 5.0, 'misestimated': True}
<__main__.DummyQueryFeatures object at 0x000001F96CBF31D0> 0 {'label': 'Q06', 'tables': ('lineitem',), 'estimated_rows': 1.0, 'actual_rows': 1.0, 'misestimated': False}
<__main__.DummyQueryFeatures object at 0x000001F96DC18160> 1 {'label': 'Q07', 'tables': ('lineitem', 'supplier', 'nation', 'orders', 'customer'), 'estimated_rows': 10020.0, 'actual_rows': 4.0, 'misestimated': True}
<__main__.DummyQueryFeatures object at 0x000001F96DC18380> 1 {'label': 'Q08', 'tables': ('customer', 'nation', 'region', 'orders', 'lineitem', 'part', 'supplier'), 'estimated_rows': 888.0, 'actual_rows': 2.0, 'misestimated': True}
<__main__.DummyQueryFeatures object at 0x000001F96DC00D50> 1 {'label': 'Q09', 'tables': ('partsupp', 'part', 'lineitem', 'supplier', 'orders', 'nation'), 'estimated_rows': 16.0, 'actual_rows': 175.0, 'misestimated': True}
<__main__.DummyQueryFeatures object at 0x000001F96DC00E50> 0 {'label': 'Q10', 'tables': ('lineitem', 'orders', 'customer', 'nation'), 'estimated_rows': 20.0, 'actual_rows': 20.0, 'misestimated': False}
<__main__.DummyQueryFeatures object at 0x000001F96D08CD70> 1 {'label': 'Q11', 'tables': ('supplier', 'nation', 'partsupp'), 'estimated_rows': 106206.0, 'actual_rows': 0.0, 'misestimated': True}
<__main__.DummyQueryFeatures object at 0x000001F96D08F020> 1 {'label': 'Q12', 'tables': ('lineitem', 'orders'), 'estimated_rows': 7.0, 'actual_rows': 2.0, 'misestimated': True}
<__main__.DummyQueryFeatures object at 0x000001F96D06F770> 1 {'label': 'Q13', 'tables': ('orders', 'customer'), 'estimated_rows': 200.0, 'actual_rows': 34.0, 'misestimated': True}
<__main__.DummyQueryFeatures object at 0x000001F96DC144B0> 0 {'label': 'Q14', 'tables': ('part', 'lineitem'), 'estimated_rows': 1.0, 'actual_rows': 1.0, 'misestimated': False}
<__main__.DummyQueryFeatures object at 0x000001F96DBCD3D0> 1 {'label': 'Q15', 'tables': ('lineitem', 'supplier'), 'estimated_rows': 485.0, 'actual_rows': 1.0, 'misestimated': True}
<__main__.DummyQueryFeatures object at 0x000001F96DC0CE90> 1 {'label': 'Q16', 'tables': ('partsupp', 'supplier', 'part'), 'estimated_rows': 154763.0, 'actual_rows': 27840.0, 'misestimated': True}
<__main__.DummyQueryFeatures object at 0x000001F96DC0CF50> 0 {'label': 'Q17', 'tables': ('lineitem', 'part'), 'estimated_rows': 1.0, 'actual_rows': 1.0, 'misestimated': False}
<__main__.DummyQueryFeatures object at 0x000001F96DC0D0D0> 0 {'label': 'Q18', 'tables': ('orders', 'lineitem', 'customer'), 'estimated_rows': 100.0, 'actual_rows': 100.0, 'misestimated': False}
<__main__.DummyQueryFeatures object at 0x000001F96DC0D190> 0 {'label': 'Q19', 'tables': ('part', 'lineitem'), 'estimated_rows': 1.0, 'actual_rows': 1.0, 'misestimated': False}
<__main__.DummyQueryFeatures object at 0x000001F96DC0D250> 0 {'label': 'Q20', 'tables': ('supplier', 'nation', 'partsupp', 'lineitem', 'part'), 'estimated_rows': 1073.0, 'actual_rows': 631.0, 'misestimated': False}
<__main__.DummyQueryFeatures object at 0x000001F96DC0D310> 1 {'label': 'Q21', 'tables': ('lineitem', 'nation', 'supplier', 'orders'), 'estimated_rows': 1.0, 'actual_rows': 100.0, 'misestimated': True}
<__main__.DummyQueryFeatures object at 0x000001F96DC0D3D0> 1 {'label': 'Q22', 'tables': ('customer', 'orders'), 'estimated_rows': 8475.0, 'actual_rows': 7.0, 'misestimated': True}
<__main__.DummyQueryFeatures object at 0x000001F96DC0D490> 1 {'label': 'stmt_1', 'tables': ('orders',), 'estimated_rows': 50004.0, 'actual_rows': 1521599.0, 'misestimated': True}
<__main__.DummyQueryFeatures object at 0x000001F96DC0D550> 0 {'label': 'stmt_2', 'tables': ('lineitem',), 'estimated_rows': 1.0, 'actual_rows': 1.0, 'misestimated': False}
<__main__.DummyQueryFeatures object at 0x000001F96DC0D610> 0 {'label': 'stmt_3', 'tables': ('nation', 'region'), 'estimated_rows': 125.0, 'actual_rows': 125.0, 'misestimated': False}
<__main__.DummyQueryFeatures object at 0x000001F96DC0D6D0> 0 {'label': 'stmt_4', 'tables': ('orders', 'customer'), 'estimated_rows': 1.0, 'actual_rows': 1.0, 'misestimated': False}
<__main__.DummyQueryFeatures object at 0x000001F96DC0D790> 0 {'label': 'stmt_5', 'tables': ('customer', 'orders', 'nation', 'lineitem'), 'estimated_rows': 1.0, 'actual_rows': 1.0, 'misestimated': False}
<__main__.DummyQueryFeatures object at 0x000001F96DC0D850> 0 {'label': 'stmt_6', 'tables': ('lineitem',), 'estimated_rows': 1.0, 'actual_rows': 1.0, 'misestimated': False}
<__main__.DummyQueryFeatures object at 0x000001F96DC0D910> 0 {'label': 'stmt_7', 'tables': ('part',), 'estimated_rows': 1.0, 'actual_rows': 1.0, 'misestimated': False}
<__main__.DummyQueryFeatures object at 0x000001F96DC0D9D0> 1 {'label': 'QX_EXPENSIVE_01', 'tables': ('lineitem', 'customer'), 'estimated_rows': 549280000.0, 'actual_rows': 33377090000.0, 'misestimated': True}
<__main__.DummyQueryFeatures object at 0x000001F96DC0DA90> 0 {'label': 'QX_EXPENSIVE_02', 'tables': ('partsupp', 'orders'), 'estimated_rows': 33377090000.0, 'actual_rows': 33377090000.0, 'misestimated': False}
<__main__.DummyQueryFeatures object at 0x000001F96DC0DB50> 0 {'label': 'Q01', 'tables': ('lineitem',), 'estimated_rows': 6.0, 'actual_rows': 4.0, 'misestimated': False}
<__main__.DummyQueryFeatures object at 0x000001F96DC0DC10> 1 {'label': 'Q02', 'tables': ('part', 'region', 'supplier', 'nation', 'partsupp'), 'estimated_rows': 1.0, 'actual_rows': 100.0, 'misestimated': True}
<__main__.DummyQueryFeatures object at 0x000001F96DC0DCD0> 0 {'label': 'Q03', 'tables': ('lineitem', 'orders', 'customer'), 'estimated_rows': 10.0, 'actual_rows': 10.0, 'misestimated': False}
<__main__.DummyQueryFeatures object at 0x000001F96DC0DD90> 0 {'label': 'Q04', 'tables': ('orders', 'lineitem'), 'estimated_rows': 5.0, 'actual_rows': 5.0, 'misestimated': False}
<__main__.DummyQueryFeatures object at 0x000001F96DC0DE50> 1 {'label': 'Q05', 'tables': ('customer', 'nation', 'region', 'orders', 'lineitem', 'supplier'), 'estimated_rows': 25.0, 'actual_rows': 5.0, 'misestimated': True}
<__main__.DummyQueryFeatures object at 0x000001F96DC0DF10> 0 {'label': 'Q06', 'tables': ('lineitem',), 'estimated_rows': 1.0, 'actual_rows': 1.0, 'misestimated': False}
<__main__.DummyQueryFeatures object at 0x000001F96DC0DFD0> 1 {'label': 'Q07', 'tables': ('customer', 'nation', 'orders', 'lineitem', 'supplier'), 'estimated_rows': 10028.0, 'actual_rows': 4.0, 'misestimated': True}
<__main__.DummyQueryFeatures object at 0x000001F96DC0E090> 1 {'label': 'Q08', 'tables': ('part', 'lineitem', 'orders', 'customer', 'nation', 'region', 'supplier'), 'estimated_rows': 2406.0, 'actual_rows': 2.0, 'misestimated': True}
<__main__.DummyQueryFeatures object at 0x000001F96DC0E150> 1 {'label': 'Q09', 'tables': ('partsupp', 'part', 'lineitem', 'supplier', 'orders', 'nation'), 'estimated_rows': 23.0, 'actual_rows': 175.0, 'misestimated': True}
<__main__.DummyQueryFeatures object at 0x000001F96DC0E210> 0 {'label': 'Q10', 'tables': ('lineitem', 'orders', 'customer', 'nation'), 'estimated_rows': 20.0, 'actual_rows': 20.0, 'misestimated': False}
<__main__.DummyQueryFeatures object at 0x000001F96DC0E2D0> 1 {'label': 'Q11', 'tables': ('supplier', 'nation', 'partsupp'), 'estimated_rows': 105691.0, 'actual_rows': 0.0, 'misestimated': True}
<__main__.DummyQueryFeatures object at 0x000001F96DC0E390> 1 {'label': 'Q12', 'tables': ('lineitem', 'orders'), 'estimated_rows': 7.0, 'actual_rows': 2.0, 'misestimated': True}
<__main__.DummyQueryFeatures object at 0x000001F96DC0E450> 1 {'label': 'Q13', 'tables': ('orders', 'customer'), 'estimated_rows': 200.0, 'actual_rows': 34.0, 'misestimated': True}
<__main__.DummyQueryFeatures object at 0x000001F96DC0E510> 0 {'label': 'Q14', 'tables': ('part', 'lineitem'), 'estimated_rows': 1.0, 'actual_rows': 1.0, 'misestimated': False}
<__main__.DummyQueryFeatures object at 0x000001F96DC0E5D0> 1 {'label': 'Q15', 'tables': ('lineitem', 'supplier'), 'estimated_rows': 486.0, 'actual_rows': 1.0, 'misestimated': True}
<__main__.DummyQueryFeatures object at 0x000001F96DC0E690> 1 {'label': 'Q16', 'tables': ('partsupp', 'supplier', 'part'), 'estimated_rows': 154078.0, 'actual_rows': 27840.0, 'misestimated': True}
<__main__.DummyQueryFeatures object at 0x000001F96DC0E750> 0 {'label': 'Q17', 'tables': ('lineitem', 'part'), 'estimated_rows': 1.0, 'actual_rows': 1.0, 'misestimated': False}
<__main__.DummyQueryFeatures object at 0x000001F96DC0E810> 0 {'label': 'Q18', 'tables': ('orders', 'lineitem', 'customer'), 'estimated_rows': 100.0, 'actual_rows': 100.0, 'misestimated': False}
<__main__.DummyQueryFeatures object at 0x000001F96DC0E8D0> 0 {'label': 'Q19', 'tables': ('part', 'lineitem'), 'estimated_rows': 1.0, 'actual_rows': 1.0, 'misestimated': False}
<__main__.DummyQueryFeatures object at 0x000001F96DC0E990> 0 {'label': 'Q20', 'tables': ('supplier', 'nation', 'partsupp', 'lineitem', 'part'), 'estimated_rows': 1068.0, 'actual_rows': 631.0, 'misestimated': False}
<__main__.DummyQueryFeatures object at 0x000001F96DC0EA50> 1 {'label': 'Q21', 'tables': ('lineitem', 'nation', 'supplier', 'orders'), 'estimated_rows': 1.0, 'actual_rows': 100.0, 'misestimated': True}
<__main__.DummyQueryFeatures object at 0x000001F96DC0EB10> 1 {'label': 'Q22', 'tables': ('customer', 'orders'), 'estimated_rows': 8000.0, 'actual_rows': 7.0, 'misestimated': True}
<__main__.DummyQueryFeatures object at 0x000001F96DC0EBD0> 1 {'label': 'stmt_1', 'tables': ('orders',), 'estimated_rows': 49994.0, 'actual_rows': 1521599.0, 'misestimated': True}
<__main__.DummyQueryFeatures object at 0x000001F96DC0EC90> 0 {'label': 'stmt_2', 'tables': ('lineitem',), 'estimated_rows': 1.0, 'actual_rows': 1.0, 'misestimated': False}
<__main__.DummyQueryFeatures object at 0x000001F96DC0ED50> 0 {'label': 'stmt_3', 'tables': ('nation', 'region'), 'estimated_rows': 125.0, 'actual_rows': 125.0, 'misestimated': False}
<__main__.DummyQueryFeatures object at 0x000001F96DC0EE10> 0 {'label': 'stmt_4', 'tables': ('orders', 'customer'), 'estimated_rows': 1.0, 'actual_rows': 1.0, 'misestimated': False}
<__main__.DummyQueryFeatures object at 0x000001F96DC0EED0> 0 {'label': 'stmt_5', 'tables': ('customer', 'orders', 'nation', 'lineitem'), 'estimated_rows': 1.0, 'actual_rows': 1.0, 'misestimated': False}
<__main__.DummyQueryFeatures object at 0x000001F96DC0EF90> 0 {'label': 'stmt_6', 'tables': ('lineitem',), 'estimated_rows': 1.0, 'actual_rows': 1.0, 'misestimated': False}
<__main__.DummyQueryFeatures object at 0x000001F96DC0F050> 0 {'label': 'stmt_7', 'tables': ('part',), 'estimated_rows': 1.0, 'actual_rows': 1.0, 'misestimated': False}
<__main__.DummyQueryFeatures object at 0x000001F96DC0F110> 1 {'label': 'QX_EXPENSIVE_01', 'tables': ('lineitem', 'customer'), 'estimated_rows': 549360000.0, 'actual_rows': 33377090000.0, 'misestimated': True}
<__main__.DummyQueryFeatures object at 0x000001F96DC0F1D0> 0 {'label': 'QX_EXPENSIVE_02', 'tables': ('partsupp', 'orders'), 'estimated_rows': 33377090000.0, 'actual_rows': 33377090000.0, 'misestimated': False}

28